# Generated by Django 3.1.2 on 2020-10-15 14:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_auto_20201015_1252'),
    ]

    operations = [
        migrations.CreateModel(
            name='CapstoneProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('grade', models.FloatField(default=0.3)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='data.course')),
            ],
        ),
    ]
