# Generated by Django 3.1.2 on 2020-10-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_capstoneproject'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CapstoneProject',
            new_name='Project',
        ),
    ]
