# Generated by Django 3.1.2 on 2020-10-16 13:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0006_auto_20201015_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date_enrolled',
            field=models.DateField(default=datetime.date(2020, 10, 16)),
        ),
    ]
