# Generated by Django 3.1.2 on 2020-10-16 13:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0007_auto_20201016_1308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='date_enrolled',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
