# Generated by Django 3.1.3 on 2023-06-29 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Choice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choice', models.TextField()),
                ('choicecorrect', models.BooleanField(default=False)),
                ('questions', models.ManyToManyField(to='onlinecourse.Question')),
            ],
        ),
    ]
