# Generated by Django 3.1.3 on 2023-06-29 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onlinecourse', '0003_submission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='gradepoint',
            field=models.FloatField(default=0),
        ),
    ]
